// Bundles timing + fixture + app into one CLASSIC script.
// Why: ES-module `import` is blocked by CORS on file://, classic <script src> is not.
// lib/timing.js stays ESM so scripts/verify-timing.mjs (the gate) keeps working in node.
// Run:  node scripts/build.mjs
import { readFileSync, writeFileSync } from 'fs';

const timing = readFileSync('lib/timing.js', 'utf8')
  .replace(/^export\s+(async\s+)?(function|const|let|var|class)/gm, '$1$2')
  .replace(/^export\s*\{[^}]*\};?\s*$/gm, '');
const fixture = readFileSync('data/rundown.json', 'utf8');
const app = readFileSync('app.js', 'utf8');

writeFileSync('bundle.js', `// GENERATED by scripts/build.mjs — do not edit. Edit lib/timing.js or app.js.
(function () {
'use strict';
${timing}
const FIXTURE = ${fixture};
${app}
window.Backtime = {
  init,
  transport: Object.fromEntries(Object.entries(T).map(([k, f]) => [k, (...a) => { f(...a); paint(); }])),
  openEditor, closeEditor, saveEditor,
  toggleFloat: page => { T.toggleFloat(page); paint(); },
  setStart: (page, hhmm) => { const err = setStart(page, hhmm); if (!err) paint(); return err; },
  state: () => S,
  reset: () => { T.reset(); paint(); },
  setClock: hhmm => { S.clockOffsetSec = parseHHMM(hhmm) - (nowSec() - S.clockOffsetSec); paint(); },
};
})();
`);
console.log('bundle.js written');
