// Bundles timing + fixture + app into one CLASSIC script.
// Why: ES-module `import` is blocked by CORS on file://, classic <script src> is not.
// lib/timing.js stays ESM so scripts/verify-timing.mjs (the gate) keeps working in node.
// Run:  node scripts/build.mjs
import { readFileSync, writeFileSync } from 'fs';

const timing = readFileSync('lib/timing.js', 'utf8')
  .replace(/^export\s+(async\s+)?(function|const|let|var|class)/gm, '$1$2')
  .replace(/^export\s*\{[^}]*\};?\s*$/gm, '');
const fixture = readFileSync('data/rundown.json', 'utf8');
const app = readFileSync('app.js', 'utf8');

writeFileSync('bundle.js', `// GENERATED by scripts/build.mjs — do not edit. Edit lib/timing.js or app.js.
(function () {
'use strict';
${timing}
const FIXTURE = ${fixture};
${app}
window.Backtime = {
  init,
  transport: Object.fromEntries(Object.entries(T).map(([k, f]) => [k, (...a) => { f(...a); paint(); }])),
  openEditor, closeEditor, saveEditor,
  toggleFloat: page => { T.toggleFloat(page); paint(); },
  setStart: (page, hhmm) => { const err = setStart(page, hhmm); if (!err) paint(); return err; },
  state: () => S,
  reset:    () => { T.resetAll(); paint(); },   // full wipe, back to the scraped fixture
  resetAll: () => { T.resetAll(); paint(); },
  resetRun: () => { T.resetRun(); paint(); },
  setClock: hhmm => { S.clockOffsetSec = parseHHMM(hhmm) - (nowSec() - S.clockOffsetSec); paint(); },
};
})();
`);
// --- standalone single-file build -------------------------------------------
// One HTML file with the CSS and JS inlined. Hand this to anyone who cannot reach
// the hosted URL -- venue and corporate firewalls routinely intercept *.vercel.app
// and the browser reports ERR_CERT_AUTHORITY_INVALID. This file needs no network,
// no server and no sibling files: AirDrop it, email it, put it on a stick.
const html = readFileSync('index.html', 'utf8');
const css = readFileSync('app.css', 'utf8');
const js = readFileSync('bundle.js', 'utf8');
const standalone = html
  .replace('<link rel="stylesheet" href="app.css">', `<style>\n${css}\n</style>`)
  .replace('<script src="bundle.js"></script>', `<script>\n${js}\n</script>`);
if (standalone.includes('href="app.css"') || standalone.includes('src="bundle.js"'))
  throw new Error('standalone build still references external assets');
writeFileSync('backtime-standalone.html', standalone);

console.log('bundle.js written');
console.log(`backtime-standalone.html written (${(standalone.length / 1024).toFixed(0)}KB, no external refs)`);
